### ISSUE TITLE
What's the difference between this plugin and strapi-plugin-navigation?

### ISSUE THREAD

**Issue by boazpoolman** [mattmilburn/strapi-plugin-menus#55]
Not sure if this is the right place to ask.
But I was wondering what is the difference between this plugin and the [strapi-plugin-navigation](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation)?

**Comment by mattmilburn** [comment]
Lol, maybe not the right place for the discussion because it's kinda hidden from the Strapi community at large. Perhaps [Strapi's Discord community](https://strapi.io/community) would yield more responses?

And I'll give you some background on my menus plugin...

In short, several years ago when I was considering Strapi as a CMS to use for making websites and other apps, I knew that allowing my users to manage their pages and navigation menus would be essential. When Strapi v3 was current, I shopped around and found the navigation plugin you mentioned and it never worked for me, no matter what I did with it. I tried reaching out to the Strapi devs but no one had answers and the plugin devs gave no response.

This is when I decided to make my own plugin and manage it myself. I couldn't wait around for others to make solutions for me and I have to admit that I never went back to check out the features of that plugin after Strapi v4 released. 😄 

I'm proud of my work on this plugin since it started over 2 years ago and I'm certainly going to continue using it and improving it. Sometimes I browse other plugins and get inspired by their features, but it's not really in the spirit of competition. It's more for the purpose of rounding out my plugins with the right features.

More is currently in the works for the menus plugin. Happy to discuss any feature requests!
