### ISSUE TITLE
How to get custom attributes through menu API

### ISSUE THREAD

**Issue by arioswebtechnologies** [mattmilburn/strapi-plugin-menus#56]
Hello all, i have added a custom attribute to get a icon through each menu item. i'm able to create DB schema and save it.

but not able to fetch the custom attribute media or any other custom values through API. can u provide any example API for custom attribute.?

![image](https://user-images.githubusercontent.com/93800154/193416600-43aaa3ad-6c88-491a-8972-48abd1f0aaf2.png)

**Comment by mattmilburn** [comment]
Hi @arioswebtechnologies Are you using the `populate` param in your API request? If you do not use this param, relation fields and other nested data will not be included in the response data. [See Strapi docs about population](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html).

**Comment by nasianss** [comment]
Hi @mattmilburn 

I'm using a few custom fields and one of them is of type "media". When I query `http://localhost:1337/api/menus/1?nested&populate=%2A` I get the values for all my other custom fields but not for the one of type "media".

Am I missing a query param?

Thank you and thanks for this amazing plugin!

**Comment by mattmilburn** [comment]
Hi @nasianss I think you need a little more to your `populate` param. See below where my URL would request a menu with id `1` and notice the extended `populate` param. Ideally you would want to build these complicated URLs using the `qs` library because it provides a nicer interface than typing this all out yourself.

```
http://localhost:1337/api/menus/1?nested&populate[items][populate][0]=dr_media
```

And if you need to populate additional/deeper relations you could keep adding to it like this. ([See Strapi docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#relation-media-fields))
```
http://localhost:1337/api/menus/1?nested&populate[items][populate][0]=dr_media&populate[items][populate][1]=another_relation
```

I will make sure to include an example of this in the README in an upcoming release 👍🏻

**Comment by nasianss** [comment]
That was it @mattmilburn ! Thank you so much 🙌

**Comment by aurelienbobenrieth** [comment]
@mattmilburn 
In that case the `nested` attribute is ignored ? 🤔
