### ISSUE TITLE
Strapi v4.5.0

### ISSUE THREAD

**Issue by Zharkan** [mattmilburn/strapi-plugin-menus#62]
There is an issue regarding relations after upgrading to Strapi v4.5.0. Downgrading Strapi doesn't seem to fix the issue, relations don't appear anymore inside the tabs if you add relations to pick from. 

Thankfully though current established relations don't seem to be affected => even if those are not displayed within the ui they're still present in the response from rest or graphql queries.

Also there's a warning in console tab : 
```
Missing metadata for <relation_name> relation field
```

**Comment by mattmilburn** [comment]
Hi @Zharkan Thanks for raising this issue. I will be testing v4.5.0 during the next week... a number of things regarding relations have caused some trouble 🤷🏻

**Comment by graphicfox** [comment]
Hello @mattmilburn!

First of all -> Thank you for this amazing plugin.
Do you already have news for us if you found out why relations are not working? Or do you might have a workaround?

**Comment by mattmilburn** [comment]
Hi @graphicfox I will have a new release ready early this week with relations working for v4.5.0 👍

This version of Strapi totally changed how relation inputs work and also changed a little bit about how the data is handled.

I will ping everyone as soon as the new release is ready.

**Comment by davtk** [comment]
+1

Just installed clean Strapi 4.5.1, installed this plugin, and nothing appear in the menu.

**Comment by thomasbrunstrom** [comment]
Any updates on this one?

**Comment by Zharkan** [comment]
He's working on it, give him time to fix this : https://github.com/mattmilburn/strapi-plugin-menus/pull/71

**Comment by Zharkan** [comment]
> Any updates on this one?

https://github.com/mattmilburn/strapi-plugin-menus/pull/71 > He's working on it, give him time to fix this :smile:

**Comment by nicknijenhuis** [comment]
Does anyone perhaps have a workaround for this one, that can be used in the meantime while this is being fixed?

**Comment by mattmilburn** [comment]
Hey everyone 👋🏻 @Zharkan @graphicfox @thomasbrunstrom @nicknijenhuis and others,

**Thank you for your patience.** The menus plugin has now updated to version 1.2.0 with compatibility for Strapi v4.5x 🎉 

This required more effort than expected because relations are no longer treated the same way in the content manager and migrating the new `RelationInput` components into the menus plugin was not a simple task.

Please let me know if you find any issues with this latest release and the new relation fields. 🙂  

If anyone is feeling generous, [you can buy me a beer](https://www.buymeacoffee.com/mattmilburn) 🍺 🍻 😄
