### ISSUE TITLE
Roles in settings return a white screen

### ISSUE THREAD

**Issue by AllanCLRS** [mattmilburn/strapi-plugin-menus#97]
Environment
```
    Strapi: 4.7.1,
    strapi-plugin-menus: 1.3.1
```

Issue
```
    Impossible to access to the roles with this plugin  
    It returns a white screen 
```
Config is not the problem because it also appears without it or with enable: false

**Comment by gloryD96** [comment]
I have the same issue 
strapi:4.6.2
menus:1.3.2

**Comment by mattmilburn** [comment]
Hi @AllanCLRS @gloryD96 There is not a fix for this within the plugin because it was coming from an issue with the users and permissions plugin in v4.7x of Strapi. Upgrading Strapi to v4.8.2 is the official solution to this issue and Strapi is highly recommending that upgrade anyway to address a security issue.
